"""удаление строки created_at

Revision ID: e224f4b9ce18
Revises: a1c6d8ef3da5
Create Date: 2025-08-28 17:38:49.743719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e224f4b9ce18'
down_revision: Union[str, Sequence[str], None] = 'a1c6d8ef3da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'created_at')
    op.alter_column('photos', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
